version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./services/web/:/home/microblog
    environment:
      FLASK_ENV: development
  # redis:
  #   image: "redis:alpine"
